/**
 * PROJECT BLOG POST: https://mostafa-samir.github.io/Tic-Tac-Toe-AI/
 * PROJECT BLOG GITHUB REPO SOURCE CODE: https://github.com/Mostafa-Samir/Tic-Tac-Toe-AI
 * 
 * THIS IS THE IMPLEMENTATION THE TIC TAC TOE GAME USING TYPESCRIPT. THE MAIN LEARNING POINT IS 
 * THE USAGE OF THE MINMAX ALGORIHM FROM ARTIFICIAL INTELLIGENCE TO IMPLEMENT AUTONOMY IN THE GAME.
 * 
 * AUTHOR: BUBUKA SHARIF
 * EMAIL: sharifbubuka256@gmail.com
 * DATE: 25-01-2022 17:40 PM (UGANDAN TIME)
 * 
 */
